import { ScrollView } from "std-widgets.slint";

export component Chat {
    width: 800px;
    height: 800px;
    ScrollView {
        width: 800px;
        height: 800px;
        viewport-width: 300px;
        viewport-height: 800px;
        Rectangle {
            width: 30px;
            height: 30px;
            x: 275px;
            y: 50px;
            background: blue;
        }

        Rectangle {
            width: 30px;
            height: 30px;
            x: 175px;
            y: 130px;
            background: red;
        }

        Rectangle {
            width: 30px;
            height: 30px;
            x: 25px;
            y: 210px;
            background: yellow;
        }

        Rectangle {
            width: 30px;
            height: 30px;
            x: 98px;
            y: 55px;
            background: orange;
        }
    }
}
