import { Button, VerticalBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    width: 400px;
    height: 400px;
    title: "Matrust";
    VerticalLayout {
        padding: 5px;
        spacing: 10px;
        alignment: center;

        LineEdit {
            font-size: 14px;
            min-width: parent.width;
            height: 30px;
            text: "";
            placeholder-text: "Username";
        }
        LineEdit {
            font-size: 14px;
            height: 30px;
            placeholder-text: "Password";
            text: "";
            input-type: password;
            min-width: parent.width;
        }
        HorizontalLayout {
            alignment: center;
            Button {
                text: "Login";
                width: 50px;
                height: 30px;
                clicked => {

                }
            }
        }
    }
}